//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookbookApp.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeSimplifiedDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class RecipeSimplifiedDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRecipeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRecipe {
            get {
                return this.IdRecipeField;
            }
            set {
                if ((this.IdRecipeField.Equals(value) != true)) {
                    this.IdRecipeField = value;
                    this.RaisePropertyChanged("IdRecipe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecipeDto", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class RecipeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRecipeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreparationDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan PreparationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataTransferObjects.IngredientDto[] RecipeIngredientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DataTransferObjects.RecipeDto adapteeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRecipe {
            get {
                return this.IdRecipeField;
            }
            set {
                if ((this.IdRecipeField.Equals(value) != true)) {
                    this.IdRecipeField = value;
                    this.RaisePropertyChanged("IdRecipe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreparationDescription {
            get {
                return this.PreparationDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PreparationDescriptionField, value) != true)) {
                    this.PreparationDescriptionField = value;
                    this.RaisePropertyChanged("PreparationDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan PreparationTime {
            get {
                return this.PreparationTimeField;
            }
            set {
                if ((this.PreparationTimeField.Equals(value) != true)) {
                    this.PreparationTimeField = value;
                    this.RaisePropertyChanged("PreparationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataTransferObjects.IngredientDto[] RecipeIngredient {
            get {
                return this.RecipeIngredientField;
            }
            set {
                if ((object.ReferenceEquals(this.RecipeIngredientField, value) != true)) {
                    this.RecipeIngredientField = value;
                    this.RaisePropertyChanged("RecipeIngredient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillLevel {
            get {
                return this.SkillLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillLevelField, value) != true)) {
                    this.SkillLevelField = value;
                    this.RaisePropertyChanged("SkillLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DataTransferObjects.RecipeDto adaptee {
            get {
                return this.adapteeField;
            }
            set {
                if ((object.ReferenceEquals(this.adapteeField, value) != true)) {
                    this.adapteeField = value;
                    this.RaisePropertyChanged("adaptee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRecipeList", ReplyAction="http://tempuri.org/IService/GetRecipeListResponse")]
        CookbookApp.ServiceReference.RecipeSimplifiedDto[] GetRecipeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRecipeList", ReplyAction="http://tempuri.org/IService/GetRecipeListResponse")]
        System.Threading.Tasks.Task<CookbookApp.ServiceReference.RecipeSimplifiedDto[]> GetRecipeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRecipe", ReplyAction="http://tempuri.org/IService/GetRecipeResponse")]
        CookbookApp.ServiceReference.RecipeDto GetRecipe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRecipe", ReplyAction="http://tempuri.org/IService/GetRecipeResponse")]
        System.Threading.Tasks.Task<CookbookApp.ServiceReference.RecipeDto> GetRecipeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddRecipe", ReplyAction="http://tempuri.org/IService/AddRecipeResponse")]
        void AddRecipe(CookbookApp.ServiceReference.RecipeDto recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AddRecipe", ReplyAction="http://tempuri.org/IService/AddRecipeResponse")]
        System.Threading.Tasks.Task AddRecipeAsync(CookbookApp.ServiceReference.RecipeDto recipe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : CookbookApp.ServiceReference.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CookbookApp.ServiceReference.IService>, CookbookApp.ServiceReference.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CookbookApp.ServiceReference.RecipeSimplifiedDto[] GetRecipeList() {
            return base.Channel.GetRecipeList();
        }
        
        public System.Threading.Tasks.Task<CookbookApp.ServiceReference.RecipeSimplifiedDto[]> GetRecipeListAsync() {
            return base.Channel.GetRecipeListAsync();
        }
        
        public CookbookApp.ServiceReference.RecipeDto GetRecipe(int id) {
            return base.Channel.GetRecipe(id);
        }
        
        public System.Threading.Tasks.Task<CookbookApp.ServiceReference.RecipeDto> GetRecipeAsync(int id) {
            return base.Channel.GetRecipeAsync(id);
        }
        
        public void AddRecipe(CookbookApp.ServiceReference.RecipeDto recipe) {
            base.Channel.AddRecipe(recipe);
        }
        
        public System.Threading.Tasks.Task AddRecipeAsync(CookbookApp.ServiceReference.RecipeDto recipe) {
            return base.Channel.AddRecipeAsync(recipe);
        }
    }
}
